# Generated by Django 5.0.1 on 2025-08-23 18:03

import django.core.validators
import django.db.models.deletion
import properties.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirtableSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('full', 'Full Sync'), ('properties', 'Properties Only'), ('configurations', 'Configurations Only'), ('images', 'Images Only'), ('amenities', 'Amenities Only')], default='full', max_length=20)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial Success')], default='started', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('properties_processed', models.PositiveIntegerField(default=0)),
                ('configurations_processed', models.PositiveIntegerField(default=0)),
                ('images_processed', models.PositiveIntegerField(default=0)),
                ('amenities_processed', models.PositiveIntegerField(default=0)),
                ('errors_count', models.PositiveIntegerField(default=0)),
                ('error_details', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('dry_run', models.BooleanField(default=False)),
                ('files_downloaded', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status'], name='properties__status_9971ed_idx'), models.Index(fields=['sync_type'], name='properties__sync_ty_6f10f3_idx'), models.Index(fields=['started_at'], name='properties__started_ab7cf9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airtable_id', models.CharField(blank=True, help_text='Airtable record ID for sync purposes', max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('brochure', models.FileField(blank=True, null=True, upload_to=properties.models.brochure_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=properties.models.property_thumbnail_path)),
                ('is_active', models.BooleanField(default=True)),
                ('luxury_status', models.CharField(choices=[('luxurious', 'Luxurious'), ('non_luxurious', 'Non-Luxurious')], default='non_luxurious', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Last time this was synced from Airtable', null=True)),
                ('completion_date', models.DateField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['airtable_id'], name='properties__airtabl_5a13ed_idx'), models.Index(fields=['slug'], name='properties__slug_4fd4e3_idx'), models.Index(fields=['is_active'], name='properties__is_acti_78cc81_idx'), models.Index(fields=['luxury_status'], name='properties__luxury__f8ed84_idx')],
            },
        ),
        migrations.CreateModel(
            name='SharedPropertyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this shared list', max_length=200)),
                ('token', models.CharField(blank=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('airtable_ids', models.JSONField(default=list, help_text='List of Airtable record IDs for the properties')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_lists', to=settings.AUTH_USER_MODEL)),
                ('properties', models.ManyToManyField(related_name='shared_lists', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('agent', 'Real Estate Agent')], default='viewer', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_employee', models.BooleanField(default=False)),
                ('can_share_properties', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airtable_id', models.CharField(blank=True, help_text='Airtable record ID for sync purposes', max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional amenity description')),
                ('icon', models.CharField(blank=True, help_text='Icon class or name', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='properties.property')),
            ],
            options={
                'verbose_name_plural': 'Property Amenities',
                'indexes': [models.Index(fields=['airtable_id'], name='properties__airtabl_d7e667_idx'), models.Index(fields=['property'], name='properties__propert_4da2d2_idx'), models.Index(fields=['name'], name='properties__name_245344_idx')],
                'unique_together': {('property', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PropertyConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airtable_id', models.CharField(blank=True, help_text='Airtable record ID for sync purposes', max_length=50, null=True, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=1)),
                ('square_footage', models.PositiveIntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='properties.property')),
            ],
            options={
                'ordering': ['bedrooms', 'price'],
                'indexes': [models.Index(fields=['airtable_id'], name='properties__airtabl_2ae36a_idx'), models.Index(fields=['property', 'is_available'], name='properties__propert_f43119_idx'), models.Index(fields=['bedrooms'], name='properties__bedroom_5b9b63_idx'), models.Index(fields=['price'], name='properties__price_1e2f18_idx')],
                'unique_together': {('property', 'type')},
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airtable_id', models.CharField(blank=True, help_text='Airtable record ID for sync purposes', max_length=50, null=True, unique=True)),
                ('image', models.ImageField(upload_to=properties.models.property_image_path)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('attachment_index', models.PositiveIntegerField(default=0, help_text='Index of attachment within Airtable record')),
                ('original_record_id', models.CharField(blank=True, help_text='Original Airtable record ID before splitting', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['airtable_id'], name='properties__airtabl_017560_idx'), models.Index(fields=['property', 'order'], name='properties__propert_94c164_idx'), models.Index(fields=['original_record_id'], name='properties__origina_6f2a4a_idx')],
            },
        ),
    ]
