# Generated by Django 5.0.1 on 2025-09-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.TextField(default='lekki'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(default='house'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
