# Generated by Django 5.0.1 on 2025-10-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_address_alter_property_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='image_url_hash',
            field=models.CharField(blank=True, help_text='SHA256 hash of image URL to detect changes', max_length=64),
        ),
    ]
