# Generated by Django 5.0.1 on 2025-11-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_propertyimage_image_url_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='unlocked_properties',
            field=models.ManyToManyField(blank=True, help_text='Properties for which this user can see exact location', related_name='unlocked_by_users', to='properties.property'),
        ),
    ]
