# Generated by Django 5.0.1 on 2025-11-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_userprofile_unlocked_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Administrator'), ('agent', 'Real Estate Agent')], max_length=20, null=True),
        ),
    ]
