# Generated by Django 5.0.1 on 2025-11-12 05:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_employeeinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airtable_id', models.CharField(blank=True, help_text='Airtable record ID for sync purposes', max_length=50, null=True, unique=True)),
                ('stage', models.CharField(choices=[('foundation', 'Foundation'), ('structure', 'Structure'), ('roofing', 'Roofing'), ('exterior', 'Exterior Finishing'), ('interior', 'Interior Finishing'), ('landscaping', 'Landscaping'), ('final_touches', 'Final Touches'), ('completed', 'Completed')], help_text='Current construction stage', max_length=20)),
                ('progress_percentage', models.PositiveIntegerField(default=0, help_text='Overall completion percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('update_date', models.DateField(default=django.utils.timezone.now, help_text='Date of this progress update')),
                ('description', models.TextField(blank=True, help_text='Details about this progress update')),
                ('uploaded_by', models.CharField(blank=True, help_text='Name or email of person who added this update', max_length=100)),
                ('is_latest', models.BooleanField(default=False, help_text='Mark if this is the most recent update for the property')),
                ('images_data', models.JSONField(blank=True, default=list, help_text='List of image attachment data from Airtable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Last time this was synced from Airtable', null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Progress Update',
                'verbose_name_plural': 'Property Progress Updates',
                'ordering': ['-update_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyProgressImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airtable_id', models.CharField(blank=True, help_text='Unique ID for this image (progress_update_id + index)', max_length=50, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=properties.models.progress_image_path)),
                ('order', models.PositiveIntegerField(default=0)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('attachment_index', models.PositiveIntegerField(default=0, help_text='Index of attachment within Airtable record')),
                ('image_url_hash', models.CharField(blank=True, help_text='SHA256 hash of image URL to detect changes', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('progress_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.propertyprogress')),
            ],
            options={
                'ordering': ['order', 'attachment_index'],
            },
        ),
        migrations.AddIndex(
            model_name='propertyprogress',
            index=models.Index(fields=['airtable_id'], name='properties__airtabl_06204f_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyprogress',
            index=models.Index(fields=['property', '-update_date'], name='properties__propert_8cf0a9_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyprogress',
            index=models.Index(fields=['stage'], name='properties__stage_77dbb8_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyprogress',
            index=models.Index(fields=['is_latest'], name='properties__is_late_52390f_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyprogressimage',
            index=models.Index(fields=['airtable_id'], name='properties__airtabl_2b40d1_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyprogressimage',
            index=models.Index(fields=['progress_update', 'order'], name='properties__progres_570581_idx'),
        ),
    ]
