# Generated by Django 5.0.1 on 2025-11-17 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_propertyfavorite'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='propertyfavorite',
            new_name='properties__user_id_59b2b2_idx',
            old_name='properties_fav_user_idx',
        ),
        migrations.RenameIndex(
            model_name='propertyfavorite',
            new_name='properties__propert_4fc30d_idx',
            old_name='properties_fav_prop_idx',
        ),
    ]
