# Generated by Django 5.0.1 on 2025-12-20 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_rename_properties_fav_user_idx_properties__user_id_59b2b2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date', null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.IntegerField(default=1, help_text='Number of times this code can be used')),
                ('use_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this invitation')),
                ('created_by', models.ForeignKey(help_text='Admin who created this invitation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_client_invitations', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, help_text='Client who used this code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_client_invitation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Invitation',
                'verbose_name_plural': 'Client Invitations',
                'ordering': ['-created_at'],
            },
        ),
    ]
