# Generated by Django 5.0.1 on 2026-02-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0010_clientinvitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="coverage_locations",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated list of cities/areas this agent covers",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="current_open_leads",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Denormalized count of currently open leads assigned to this agent",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="current_overdue_leads",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Denormalized count of overdue leads assigned to this agent",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_available",
            field=models.BooleanField(
                default=True,
                help_text="Agent can toggle offline to pause lead assignment",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_assigned_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of most recent lead assignment (used for tie-breaking)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="on_leave_until",
            field=models.DateField(
                blank=True,
                help_text="If set and today <= this date, agent is excluded from assignment",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="property_specialties",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated list of property categories this agent specialises in",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="response_score",
            field=models.FloatField(
                default=1.0,
                help_text="0.0–1.0 ratio of leads contacted within SLA (last 30 days). Recomputed daily.",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="total_leads_assigned",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="total_leads_won",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="whatsapp_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
