# Generated by Django 5.0.1 on 2026-07-01 15:51

from django.db import migrations, models

from properties.location_utils import extract_location


def backfill_location(apps, schema_editor):
    """Populate location for existing rows by inferring it from the address."""
    Property = apps.get_model('properties', 'Property')
    for prop in Property.objects.all().only('id', 'address', 'location'):
        prop.location = extract_location(prop.address)
        prop.save(update_fields=['location'])


def clear_location(apps, schema_editor):
    Property = apps.get_model('properties', 'Property')
    Property.objects.update(location='')


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_crm_agent_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(blank=True, choices=[('Ikoyi', 'Ikoyi'), ('Lekki Phase 1', 'Lekki Phase 1'), ('Victoria Island', 'Victoria Island'), ('Lekki', 'Lekki'), ('Others', 'Others')], db_index=True, help_text='Location group used for filtering. Leave blank to auto-derive from the address.', max_length=50),
        ),
        migrations.RunPython(backfill_location, clear_location),
    ]
