# Generated by Django 5.0.1 on 2026-07-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_property_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
