# Generated by Django 5.0.1 on 2026-07-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_syncstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyconfiguration',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
