# Generated by Django 5.0.1 on 2026-07-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_alter_propertyconfiguration_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='brochure_url_hash',
            field=models.CharField(blank=True, help_text='SHA256 hash of brochure URL to detect changes', max_length=64),
        ),
        migrations.AddField(
            model_name='property',
            name='thumbnail_url_hash',
            field=models.CharField(blank=True, help_text='SHA256 hash of thumbnail URL to detect changes', max_length=64),
        ),
    ]
