# Generated by Django 5.0.1 on 2026-09-20 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_property_brochure_url_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeighbourhoodProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_slug', models.SlugField(help_text='URL slug of the market this copy belongs to, e.g. ikoyi or banana-island.', unique=True)),
                ('overview', models.TextField(blank=True, help_text='Neighbourhood overview. Leave blank to show a factual paragraph built from the numbers.')),
                ('commentary', models.TextField(blank=True, help_text="Market commentary, shown above the generated 'What the numbers say' points.")),
                ('guide_title', models.CharField(blank=True, help_text='Title of the downloadable guide.', max_length=200)),
                ('guide_file', models.FileField(blank=True, help_text='Guide PDF. The download section only appears once a file is uploaded.', upload_to='guides/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['market_slug'],
            },
        ),
        migrations.CreateModel(
            name='NeighbourhoodFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='properties.neighbourhoodprofile')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
