from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('request-access/', views.request_access_view, name='request_access'),
    path('employee-register/', views.employee_register_view, name='employee_register'),
    path('api/properties/', views.properties_api, name='properties_api'),
    path('api/properties/<int:property_id>/', views.property_detail_api, name='property_detail_api'),
    path('api/properties/<int:property_id>/favorite/', views.toggle_favorite, name='toggle_favorite'),
    path('favorites/', views.favorites_view, name='favorites'),
    path('api/create-shared-list/', views.create_shared_list, name='create_shared_list'),
    path('property/<int:property_id>/pdf/', views.download_property_pdf, name='property_pdf'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('manage-shares/', views.manage_shared_lists, name='manage_shared_lists'),
    path('manage-shares/delete/<int:list_id>/', views.delete_shared_list, name='delete_shared_list'),
    path('manage-shares/toggle/<int:list_id>/', views.toggle_shared_list, name='toggle_shared_list'),
    path('api/property/<int:property_id>/request-unlock/', views.request_property_unlock, name='request_property_unlock'),
    path('api/compare-properties/', views.compare_properties, name='compare_properties'),
    path('api/comparison-properties/<str:property_ids>/', views.comparison_pdf, name='comparison_pdf'),
    path('api/chat/', views.chat_proxy, name='chat_proxy'),
    path('api/validate-invitation/', views.validate_invitation_code, name='validate_invitation'),
    path('google-oauth-signup/', views.google_oauth_with_invitation, name='google_oauth_signup'),
    path('shared/<str:token>/', views.shared_properties_view, name='shared_properties'),
    path('property/<int:property_pk>/<slug:slug>/', views.property_detail_view, name='property_detail'),
    # Legacy id-only URL (older links, WhatsApp shares): 301s to the slug URL above.
    path('property/<int:property_pk>/', views.property_detail_view, name='property_detail'),
    path('neighbourhoods/', views.neighbourhood_index_view, name='neighbourhood_index'),
    path('neighbourhoods/<slug:location_slug>/', views.neighbourhood_detail_view, name='neighbourhood_detail'),
    path('compare/', views.compare_neighbourhoods_view, name='compare_neighbourhoods_index'),
    path('compare/<slug:pair>/', views.compare_neighbourhoods_view, name='compare_neighbourhoods'),
    path('temp2/', views.temp_view, name='temp2'),
    path('portfolio/', views.temp_view, name='temp'),
    path('reports/', views.reports_view, name='reports'),
    path('', views.public_homepage_view, name='home'),
]
