"""
Django settings for miniapp project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
try:
    from decouple import config
except ImportError:
    from decouple import Config
    config = Config()
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMP_DIR = os.path.join(BASE_DIR, "templates")
STATIC_DIR = os.path.join(BASE_DIR, "static")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default=None)
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = ['127.0.0.1', 
                'localhost', 
                '18.188.180.17', 
                'offplan.cwlagos.com', 
                '0.0.0.0', 
                '3.129.25.168']


# Application definition

INSTALLED_APPS = [
    "whitenoise.runserver_nostatic",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sites',  # Required for allauth

    # Third-party apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    # Local apps
    'properties',
    'crm',
    "storages",
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Required for allauth
    'csp.middleware.CSPMiddleware',
]

ROOT_URLCONF = 'miniapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMP_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',  # Required for allauth
            ],
        },
    },
]

WSGI_APPLICATION = 'miniapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases



# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    STATIC_DIR,
]

STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'temp'
LOGOUT_REDIRECT_URL = 'login'
LOGIN_URL = 'login'

# Django Allauth Configuration
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Allauth settings - Modern configuration
ACCOUNT_EMAIL_VERIFICATION = 'optional'  # Set to 'mandatory' in production
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_ADAPTER = 'properties.adapters.CustomAccountAdapter'

# Suppress allauth default messages to avoid stale messages
ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS = True
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = False

# Modern allauth field configuration
ACCOUNT_LOGIN_METHODS = {'email', 'username'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'first_name', 'last_name', 'password1*', 'password2*']

# Social Account settings
SOCIALACCOUNT_ADAPTER = 'properties.adapters.CustomSocialAccountAdapter'
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_QUERY_EMAIL = True

# Google OAuth settings
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'APP': {
            'client_id': config('GOOGLE_OAUTH_CLIENT_ID', default=''),
            'secret': config('GOOGLE_OAUTH_CLIENT_SECRET', default=''),
            'key': ''
        }
    }
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'airtable-cache',
    }
}
# PDF Generation Settings
PDF_SETTINGS = {
    'MAX_IMAGE_WIDTH': 400,
    'MAX_IMAGE_HEIGHT': 300,
    'IMAGE_QUALITY': 85,
    'REQUEST_TIMEOUT': 10,  # seconds for downloading remote images
}

# Security settings for file downloads
SECURE_CROSS_ORIGIN_OPENER_POLICY = None  # Allow PDF downloads
SECURE_REFERRER_POLICY = "same-origin"

# Content Security Policy (if using django-csp)
CSP_DEFAULT_SRC = ["'self'"]
CSP_SCRIPT_SRC = ["'self'", "'unsafe-inline'", "https://cdn.tailwindcss.com", "https://cdnjs.cloudflare.com"]
CSP_STYLE_SRC = ["'self'", "'unsafe-inline'", "https://cdnjs.cloudflare.com", "https://fonts.googleapis.com"]
CSP_FONT_SRC = ["'self'", "https://cdnjs.cloudflare.com", "https://fonts.gstatic.com"]
CSP_CONNECT_SRC = ["'self'"]
CSP_FORM_ACTION = ["'self'"]

# Session Settings
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Use database-backed sessions
SESSION_COOKIE_SAMESITE = 'Lax'  # Allow cookies in same-site context
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie
SESSION_SAVE_EVERY_REQUEST = True  # Ensure session is saved on every request



# CSRF Settings
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to read CSRF token
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_USE_SESSIONS = False  # Use cookie-based CSRF tokens instead of session
CSRF_TRUSTED_ORIGINS = [
    "https://offplan.cwlagos.com",
]



# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB

# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'  # Optional: Set to your timezone (e.g., 'America/New_York')


# AWS Stuff

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres',
        'PASSWORD': config("AWS_DATABASE_PASSWORD"),
        'HOST': 'realestatedb.c1k6u4kg29d6.us-east-2.rds.amazonaws.com',
        'PORT': '5432',
    }
}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID', default=None)
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY', default=None)

AWS_STORAGE_BUCKET_NAME = config("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION_NAME = "us-east-2"

CSP_IMG_SRC = [
    "'self'",
    "data:",
    "blob:",
    f"https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com",
    f"https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com",
    # optional, broader:
    "https://*.amazonaws.com",
    # if/when you switch to CloudFront:
    # f"https://{AWS_S3_CUSTOM_DOMAIN}",
    # or a wildcard if you prefer:
    # "https://*.cloudfront.net",
]
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_S3_FILE_OVERWRITE = True            # keep original filenames unique
AWS_DEFAULT_ACL = None                    # ACLs disabled (recommended)
AWS_QUERYSTRING_AUTH = False

#MEDIA_URL = f"https://d2l0rj12cmje55.cloudfront.net/"
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
DATA_UPLOAD_MAX_MEMORY_SIZE = 26214400     # 25MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 26214400
#AWS_S3_CUSTOM_DOMAIN = "d2l0rj12cmje55.cloudfront.net"  # << add this # Ill uncomment this when i create cloud front
#AWS_S3_OBJECT_PARAMETERS = {"CacheControl": "max-age=31536000, public"}  # good caching

# N8N Chat Widget Settings
N8N_CHAT_WEBHOOK_URL = config('N8N_CHAT_WEBHOOK_URL')

# CRM / SendGrid Settings
SENDGRID_API_KEY = config('SENDGRID_API_KEY', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='cwresocial@gmail.com')
SITE_URL = config('SITE_URL', default='http://localhost:8000')

# CRM SLA defaults (overridable via SLAConfig model)
CRM_SLA_HOURS = 2
CRM_DEDUP_WINDOW_HOURS = 6
CRM_ESCALATION_HOURS = 24

# HTTPS / transport security — enabled in deployed (HTTPS) environments only.
deployment = config('DEPLOYMENT', default=False, cast=bool)
SECURE_SSL_REDIRECT = deployment
CSRF_COOKIE_SECURE = deployment
SESSION_COOKIE_SECURE = deployment
# 1 year HSTS in production; only enable PRELOAD once HTTPS is confirmed site-wide.
SECURE_HSTS_SECONDS = 31536000 if deployment else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = deployment
SECURE_HSTS_PRELOAD = deployment

if deployment:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

CSRF_TRUSTED_ORIGINS = [config('SITE_URL', default='http://localhost:8000')]
USE_X_FORWARDED_HOST = True