# Generated by Django 5.0.1 on 2026-02-11 02:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("properties", "0011_crm_agent_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "property_title_snapshot",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "property_location_snapshot",
                    models.CharField(blank=True, max_length=300),
                ),
                ("property_url_snapshot", models.URLField(blank=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("message", models.TextField()),
                (
                    "lead_status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("CONTACTED", "Contacted"),
                            ("VIEWING_SCHEDULED", "Viewing Scheduled"),
                            ("NEGOTIATION", "Negotiation"),
                            ("WON", "Won"),
                            ("LOST", "Lost"),
                            ("UNRESPONSIVE", "Unresponsive"),
                        ],
                        default="NEW",
                        max_length=30,
                    ),
                ),
                (
                    "followup_status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("OVERDUE", "Overdue"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                ("utm_source", models.CharField(blank=True, max_length=100)),
                ("utm_medium", models.CharField(blank=True, max_length=100)),
                ("utm_campaign", models.CharField(blank=True, max_length=100)),
                ("utm_term", models.CharField(blank=True, max_length=100)),
                ("ip_address_hash", models.CharField(blank=True, max_length=64)),
                ("is_duplicate", models.BooleanField(default=False)),
                ("sla_deadline", models.DateTimeField()),
                ("consent_given", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicates",
                        to="crm.lead",
                    ),
                ),
                (
                    "related_property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="properties.property",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.leadsource",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SLAConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_contact_hours",
                    models.PositiveSmallIntegerField(
                        default=2,
                        help_text="Hours within which the agent must make first contact",
                    ),
                ),
                (
                    "escalation_overdue_hours",
                    models.PositiveSmallIntegerField(
                        default=24,
                        help_text="Hours after SLA deadline before admin is escalated",
                    ),
                ),
                (
                    "dedup_window_hours",
                    models.PositiveSmallIntegerField(
                        default=6,
                        help_text="Hours within which a re-submission of the same email+property is treated as a duplicate",
                    ),
                ),
                ("business_hours_start", models.TimeField(default="08:00")),
                ("business_hours_end", models.TimeField(default="18:00")),
                (
                    "business_days",
                    models.JSONField(
                        default=list,
                        help_text="ISO weekday numbers: 1=Mon, 7=Sun. Default [1,2,3,4,5]",
                    ),
                ),
                (
                    "w1_open_leads",
                    models.FloatField(
                        default=0.35, help_text="Weight for normalised open leads"
                    ),
                ),
                (
                    "w2_overdue_leads",
                    models.FloatField(
                        default=0.25, help_text="Weight for normalised overdue leads"
                    ),
                ),
                (
                    "w3_response_score",
                    models.FloatField(
                        default=0.2, help_text="Weight for agent response score"
                    ),
                ),
                (
                    "w4_location_match",
                    models.FloatField(
                        default=0.12, help_text="Weight for location match"
                    ),
                ),
                (
                    "w5_specialty_match",
                    models.FloatField(
                        default=0.08, help_text="Weight for specialty match"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SLA Configuration",
                "verbose_name_plural": "SLA Configuration",
            },
        ),
        migrations.CreateModel(
            name="FollowUp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("due_at", models.DateTimeField()),
                (
                    "followup_type",
                    models.CharField(
                        choices=[
                            ("CALL", "Call"),
                            ("EMAIL", "Email"),
                            ("WHATSAPP", "WhatsApp"),
                            ("MEETING", "Meeting"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("OVERDUE", "Overdue"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="followups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_followups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followups",
                        to="crm.lead",
                    ),
                ),
            ],
            options={
                "ordering": ["due_at"],
                "indexes": [
                    models.Index(
                        fields=["lead", "status"], name="crm_followu_lead_id_6e8160_idx"
                    ),
                    models.Index(
                        fields=["agent", "due_at"],
                        name="crm_followu_agent_i_d64f4b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recipient_email", models.EmailField(max_length=254)),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("VISITOR", "Visitor"),
                            ("AGENT", "Agent"),
                            ("ADMIN", "Admin"),
                        ],
                        max_length=10,
                    ),
                ),
                ("template_name", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=300)),
                ("provider_message_id", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                            ("BOUNCED", "Bounced"),
                            ("DELIVERED", "Delivered"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("idempotency_key", models.CharField(max_length=400, unique=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="crm.lead",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["lead", "status"], name="crm_emaillo_lead_id_02df23_idx"
                    ),
                    models.Index(
                        fields=["idempotency_key"],
                        name="crm_emaillo_idempot_990b2e_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("LEAD_CREATED", "Lead Created"),
                            ("STATUS_CHANGED", "Status Changed"),
                            ("AGENT_ASSIGNED", "Agent Assigned"),
                            ("AGENT_REASSIGNED", "Agent Reassigned"),
                            ("CALL_LOGGED", "Call Logged"),
                            ("EMAIL_SENT", "Email Sent"),
                            ("WHATSAPP_LOGGED", "WhatsApp Logged"),
                            ("NOTE_ADDED", "Note Added"),
                            ("FOLLOWUP_SCHEDULED", "Follow-Up Scheduled"),
                            ("FOLLOWUP_COMPLETED", "Follow-Up Completed"),
                            ("OVERDUE_FLAGGED", "Marked Overdue"),
                            ("ESCALATED", "Escalated to Admin"),
                            ("DUPLICATE_DETECTED", "Duplicate Detected"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "contact_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EMAIL", "Email"),
                            ("PHONE", "Phone"),
                            ("WHATSAPP", "WhatsApp"),
                            ("IN_PERSON", "In Person"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("old_value", models.CharField(blank=True, max_length=100)),
                ("new_value", models.CharField(blank=True, max_length=100)),
                ("note", models.TextField(blank=True)),
                ("is_private", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="crm.lead",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["lead", "event_type"],
                        name="crm_activit_lead_id_0e3256_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="crm_activit_created_5dbfb2_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LeadAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "assignment_reason",
                    models.CharField(
                        choices=[
                            ("SCORE_BASED", "Score Based"),
                            ("ROUND_ROBIN", "Round Robin"),
                            ("MANUAL", "Manual"),
                            ("FALLBACK", "Fallback (No Agents)"),
                        ],
                        default="SCORE_BASED",
                        max_length=20,
                    ),
                ),
                ("score_snapshot", models.JSONField(blank=True, default=dict)),
                ("is_current", models.BooleanField(default=True)),
                ("admin_note", models.TextField(blank=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("unassigned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="crm.lead",
                    ),
                ),
            ],
            options={
                "ordering": ["-assigned_at"],
                "indexes": [
                    models.Index(
                        fields=["lead", "is_current"],
                        name="crm_leadass_lead_id_de87f9_idx",
                    ),
                    models.Index(
                        fields=["agent", "is_current"],
                        name="crm_leadass_agent_i_ee8088_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["email", "related_property"], name="crm_lead_email_266959_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["lead_status"], name="crm_lead_lead_st_e07da5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["followup_status"], name="crm_lead_followu_d87fc7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["sla_deadline"], name="crm_lead_sla_dea_19cef4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["created_at"], name="crm_lead_created_d9bbc3_idx"
            ),
        ),
    ]
